using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.UI;

namespace IdleRPG.UI
{
    /// <summary>
    /// Safety net for UI input. The project uses the new Input System exclusively, so the
    /// EventSystem needs its own action asset; when a scene is generated by tooling that asset
    /// can end up as a dangling reference, which silently kills every pointer click.
    ///
    /// This component re-creates the default UI actions at runtime when that happens, so buttons
    /// always respond in the Editor and in builds.
    /// </summary>
    [RequireComponent(typeof(EventSystem))]
    [RequireComponent(typeof(InputSystemUIInputModule))]
    public sealed class UiInputBootstrap : MonoBehaviour
    {
        private void Awake()
        {
            InputSystemUIInputModule module = GetComponent<InputSystemUIInputModule>();

            if (module == null)
            {
                Debug.LogError("[UiInputBootstrap] No InputSystemUIInputModule on the EventSystem.");
                return;
            }

            if (module.actionsAsset != null && module.point != null && module.leftClick != null)
            {
                return;
            }

            module.AssignDefaultActions();
            Debug.Log("[UiInputBootstrap] Rebuilt default UI input actions (the serialized ones were missing).");
        }
    }
}